name: slim_way_flutter
description: A comprehensive health and fitness tracking application.

publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: '^3.8.0'
  flutter: '^3.32.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  slim_way_client:
    path: ../slim_way_client
  serverpod_flutter: 3.2.3
  serverpod_auth_client: 3.2.3
  serverpod_auth_shared_flutter: 3.2.3
  serverpod_auth_email_flutter: 3.2.3
  serverpod_auth_google_flutter: 3.2.3
  google_sign_in: ^6.3.0
  mobile_scanner: ^5.2.2
  http: ^1.2.1
  
  # UI & Utils
  easy_localization: ^3.0.7
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  fl_chart: ^0.66.0
  image_picker: ^1.1.2
  intl: ^0.20.0
  google_fonts: ^6.2.0
  uuid: ^4.3.3
  flutter_svg: ^2.0.17
  pedometer: ^4.1.1
  percent_indicator: ^4.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^12.0.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  lottie: ^3.1.2
  vibration: ^2.0.1
  health: ^13.1.4
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#1C1C1E"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/langs/
    - assets/images/
dependency_overrides:
  flutter_secure_storage: ^10.0.0
